### ISSUE TITLE
Write a more descriptive README

### ISSUE THREAD

**Issue by tandao0909** [thangquang09/DataScience#1]
It would be better to write a more detail README. 
For example: 
- Add some more detail about the purpose of this project. 
- In this specific project, you are trying to predict the rate of survivor of titanic dataset (quite a classic one), so it'd be great if you add some details about input and output. 
- Also, some comment about the data itself (your data insight).

**Comment by thangquang09** [comment]
OK, thank you for giving me a good idea, I'll fix that.
